### ISSUE TITLE
clusteroperator resource needs to be created after operator deployment

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-svcat-apiserver-operator#13]
i'm surprised this isn't blocking the installer and failing e2e, but in your manifests you need to order the resource that deploys your operator *before* your clusteroperator resource.

As soon as the clusteroperator resource is created, the CVO will block waiting for it to report availble=true, which it won't do since the thing that will update it to available=true doesn't exist yet (your operator deployment).

@jwforres not sure what this means for the current CI setup?  Or maybe this operator just isn't being pulled into the CVO payload yet?

**Comment by bparees** [comment]
see:
https://github.com/openshift/cluster-openshift-apiserver-operator/blob/master/manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml
https://github.com/openshift/cluster-openshift-apiserver-operator/blob/master/manifests/0000_61_openshift-apiserver-operator_08_clusteroperator.yaml

**Comment by jboyd01** [comment]
Hey Ben, thanks for the review.  This is not being installed by the CVO yet - the images are not properly marked for that.  I'm still working through some issues.  When I manually install I was seeing errors during Operator startup indicating the CR didn't exist so the status couldn't be set, hence I messed with the order.  I was unaware of the condition you identified in the description, thanks, I'll reorder this.

**Comment by bparees** [comment]
> When I manually install I was seeing errors during Operator startup indicating the CR didn't exist so the status couldn't be set,

yeah i think that's ok and it should just retry until it can.  @deads2k can confirm (or you can review how the clusteroperatorcontroller bits from library-go behave)
